// This file is auto-generated by @hey-api/openapi-ts

import type { BlogApiPostsListResponse } from "./types.gen";

const postSchemaResponseTransformer = (data: any) => {
  if (data.release_date) {
    data.release_date = new Date(data.release_date);
  }
  return data;
};

export const blogApiPostsListResponseTransformer = async (
  data: any
): Promise<BlogApiPostsListResponse> => {
  data = data.map((item: any) => {
    return postSchemaResponseTransformer(item);
  });
  return data;
};
