// This file is auto-generated by @hey-api/openapi-ts

import { z } from "zod";

export const zActivity = z.object({
  id: z
    .string()
    .max(50)
    .regex(/^[-a-zA-Z0-9_]+$/),
  name: z.string().max(100),
  title: z.union([z.string().max(100), z.null()]).optional(),
  slogan: z.string().max(255).optional(),
  observatory: z.string().max(50),
  key_visual_en: z.string().readonly(),
  key_visual_es: z.string().readonly(),
  duration: z.string().optional(),
  safety_tech_doc: z.string().readonly(),
  conduct_tech_doc: z.string().readonly(),
  liability_tech_doc: z.string().readonly(),
  safety_tech_doc_es: z.string().readonly(),
  conduct_tech_doc_es: z.string().readonly(),
  liability_tech_doc_es: z.string().readonly(),
  group_safety_tech_doc: z.string().readonly(),
  group_liability_tech_doc: z.string().readonly(),
  group_safety_tech_doc_es: z.string().readonly(),
  group_liability_tech_doc_es: z.string().readonly(),
});

export const zAnnouncement = z.object({
  id: z
    .string()
    .max(50)
    .regex(/^[-a-zA-Z0-9_]+$/),
  lang: z.string().max(7).optional(),
  url: z.string().readonly(),
  title: z.string().max(200),
  subtitle: z.string().max(255).optional(),
  description: z.string().optional(),
  contacts: z.string().optional(),
  links: z.string().optional(),
  featured: z.boolean().optional(),
  release_date: z.string().readonly(),
  programs: z.array(
    z.object({
      slug: z.string(),
      name: z.string().max(255),
      logo_url: z.union([z.string().url().max(255), z.null()]).optional(),
    })
  ),
  images: z
    .array(
      z.object({
        id: z
          .string()
          .max(50)
          .regex(/^[-a-zA-Z0-9_]+$/),
        url: z.string().readonly(),
        lang: z.string().max(7).optional(),
        source: z.union([z.string(), z.null()]).optional(),
        title: z.string().max(255),
        width: z
          .union([z.number().int().gte(0).lte(2147483647), z.null()])
          .optional(),
        height: z
          .union([z.number().int().gte(0).lte(2147483647), z.null()])
          .optional(),
        featured: z.boolean().optional(),
        categories: z.array(
          z.object({
            slug: z.string(),
            name: z.string().max(255),
            logo_url: z.union([z.string().url().max(255), z.null()]).optional(),
          })
        ),
        formats: z
          .object({
            banner1920: z.union([z.string(), z.null()]).optional(),
            eps: z.union([z.string(), z.null()]).optional(),
            illustrator: z.union([z.string(), z.null()]).optional(),
            illustrator_text: z.union([z.string(), z.null()]).optional(),
            large: z.union([z.string(), z.null()]).optional(),
            medium: z.union([z.string(), z.null()]).optional(),
            news: z.union([z.string(), z.null()]).optional(),
            newsfeature: z.union([z.string(), z.null()]).optional(),
            newsmini: z.union([z.string(), z.null()]).optional(),
            original: z.union([z.string(), z.null()]).optional(),
            pdf: z.union([z.string(), z.null()]).optional(),
            pl_original: z.union([z.string(), z.null()]).optional(),
            pl_screen: z.union([z.string(), z.null()]).optional(),
            pl_thumbs: z.union([z.string(), z.null()]).optional(),
            portrait1080: z.union([z.string(), z.null()]).optional(),
            poster400y: z.union([z.string(), z.null()]).optional(),
            potwmedium: z.union([z.string(), z.null()]).optional(),
            publicationjpg: z.union([z.string(), z.null()]).optional(),
            publicationtiff: z.union([z.string(), z.null()]).optional(),
            publicationtiff10k: z.union([z.string(), z.null()]).optional(),
            publicationtiff25k: z.union([z.string(), z.null()]).optional(),
            publicationtiff40k: z.union([z.string(), z.null()]).optional(),
            screen: z.union([z.string(), z.null()]).optional(),
            screen640: z.union([z.string(), z.null()]).optional(),
            thumb150y: z.union([z.string(), z.null()]).optional(),
            thumb300y: z.union([z.string(), z.null()]).optional(),
            thumb350x: z.union([z.string(), z.null()]).optional(),
            thumb700x: z.union([z.string(), z.null()]).optional(),
            thumbs: z.union([z.string(), z.null()]).optional(),
            wallpaper1: z.union([z.string(), z.null()]).optional(),
            wallpaper2: z.union([z.string(), z.null()]).optional(),
            wallpaper3: z.union([z.string(), z.null()]).optional(),
            wallpaper4: z.union([z.string(), z.null()]).optional(),
            wallpaper5: z.union([z.string(), z.null()]).optional(),
            wallpaperthumbs: z.union([z.string(), z.null()]).optional(),
            zoomable: z.union([z.string(), z.null()]).optional(),
          })
          .readonly(),
      })
    )
    .readonly(),
  videos: z
    .array(
      z.object({
        id: z
          .string()
          .max(50)
          .regex(/^[-a-zA-Z0-9_]+$/),
        url: z.string().readonly(),
        lang: z.string().max(7).optional(),
        source: z.union([z.string(), z.null()]).optional(),
        title: z.string().max(255),
        featured: z.boolean().optional(),
        duration: z.union([z.string().readonly(), z.null()]).readonly(),
        categories: z.array(
          z.object({
            slug: z.string(),
            name: z.string().max(255),
            logo_url: z.union([z.string().url().max(255), z.null()]).optional(),
          })
        ),
        youtube_video_id: z.union([z.string().max(11), z.null()]).optional(),
        use_youtube: z.boolean().optional(),
        formats: z
          .object({
            broadcast_sd: z.union([z.string(), z.null()]).optional(),
            cylindrical_16kmaster: z.union([z.string(), z.null()]).optional(),
            cylindrical_4kmaster: z.union([z.string(), z.null()]).optional(),
            cylindrical_8kmaster: z.union([z.string(), z.null()]).optional(),
            cylindrical_preview: z.union([z.string(), z.null()]).optional(),
            dome_2kmaster: z.union([z.string(), z.null()]).optional(),
            dome_2kplayback: z.union([z.string(), z.null()]).optional(),
            dome_4kmaster: z.union([z.string(), z.null()]).optional(),
            dome_4kplayback: z.union([z.string(), z.null()]).optional(),
            dome_8kmaster: z.union([z.string(), z.null()]).optional(),
            dome_mov: z.union([z.string(), z.null()]).optional(),
            dome_preview: z.union([z.string(), z.null()]).optional(),
            ext_highres: z.union([z.string(), z.null()]).optional(),
            ext_playback: z.union([z.string(), z.null()]).optional(),
            hd_1080_broadcast: z.union([z.string(), z.null()]).optional(),
            hd_1080_screen: z.union([z.string(), z.null()]).optional(),
            hd_1080p25_broadcast: z.union([z.string(), z.null()]).optional(),
            hd_1080p25_screen: z.union([z.string(), z.null()]).optional(),
            hd_and_apple: z.union([z.string(), z.null()]).optional(),
            hd_broadcast_720p25: z.union([z.string(), z.null()]).optional(),
            hd_broadcast_720p50: z.union([z.string(), z.null()]).optional(),
            large_qt: z.union([z.string(), z.null()]).optional(),
            medium_flash: z.union([z.string(), z.null()]).optional(),
            medium_mpeg1: z.union([z.string(), z.null()]).optional(),
            medium_podcast: z.union([z.string(), z.null()]).optional(),
            news: z.union([z.string(), z.null()]).optional(),
            newsfeature: z.union([z.string(), z.null()]).optional(),
            newsmini: z.union([z.string(), z.null()]).optional(),
            old_video: z.union([z.string(), z.null()]).optional(),
            original: z.union([z.string(), z.null()]).optional(),
            potwmedium: z.union([z.string(), z.null()]).optional(),
            qtvr: z.union([z.string(), z.null()]).optional(),
            script: z.union([z.string(), z.null()]).optional(),
            small_flash: z.union([z.string(), z.null()]).optional(),
            small_qt: z.union([z.string(), z.null()]).optional(),
            thumb: z.union([z.string(), z.null()]).optional(),
            thumb300y: z.union([z.string(), z.null()]).optional(),
            thumb350x: z.union([z.string(), z.null()]).optional(),
            ultra_hd: z.union([z.string(), z.null()]).optional(),
            ultra_hd_8k_broadcast: z.union([z.string(), z.null()]).optional(),
            ultra_hd_8k_h265: z.union([z.string(), z.null()]).optional(),
            ultra_hd_broadcast: z.union([z.string(), z.null()]).optional(),
            ultra_hd_h265: z.union([z.string(), z.null()]).optional(),
            videoframe: z.union([z.string(), z.null()]).optional(),
            vr_16kmaster: z.union([z.string(), z.null()]).optional(),
            vr_2k_sos: z.union([z.string(), z.null()]).optional(),
            vr_4k: z.union([z.string(), z.null()]).optional(),
            vr_4k_sos: z.union([z.string(), z.null()]).optional(),
            vr_4kmaster: z.union([z.string(), z.null()]).optional(),
            vr_8k: z.union([z.string(), z.null()]).optional(),
            vr_8kmaster: z.union([z.string(), z.null()]).optional(),
          })
          .readonly(),
      })
    )
    .readonly(),
});

export const zAnnouncementMini = z.object({
  id: z
    .string()
    .max(50)
    .regex(/^[-a-zA-Z0-9_]+$/),
  lang: z.string().max(7).optional(),
  url: z.string().readonly(),
  title: z.string().max(200),
  subtitle: z.string().max(255).optional(),
  release_date: z.string().readonly(),
  programs: z.array(
    z.object({
      slug: z.string(),
      name: z.string().max(255),
      logo_url: z.union([z.string().url().max(255), z.null()]).optional(),
    })
  ),
  main_image: z.object({
    id: z
      .string()
      .max(50)
      .regex(/^[-a-zA-Z0-9_]+$/),
    url: z.string().readonly(),
    lang: z.string().max(7).optional(),
    source: z.union([z.string(), z.null()]).optional(),
    title: z.string().max(255),
    width: z
      .union([z.number().int().gte(0).lte(2147483647), z.null()])
      .optional(),
    height: z
      .union([z.number().int().gte(0).lte(2147483647), z.null()])
      .optional(),
    featured: z.boolean().optional(),
    categories: z.array(
      z.object({
        slug: z.string(),
        name: z.string().max(255),
        logo_url: z.union([z.string().url().max(255), z.null()]).optional(),
      })
    ),
    formats: z
      .object({
        banner1920: z.union([z.string(), z.null()]).optional(),
        eps: z.union([z.string(), z.null()]).optional(),
        illustrator: z.union([z.string(), z.null()]).optional(),
        illustrator_text: z.union([z.string(), z.null()]).optional(),
        large: z.union([z.string(), z.null()]).optional(),
        medium: z.union([z.string(), z.null()]).optional(),
        news: z.union([z.string(), z.null()]).optional(),
        newsfeature: z.union([z.string(), z.null()]).optional(),
        newsmini: z.union([z.string(), z.null()]).optional(),
        original: z.union([z.string(), z.null()]).optional(),
        pdf: z.union([z.string(), z.null()]).optional(),
        pl_original: z.union([z.string(), z.null()]).optional(),
        pl_screen: z.union([z.string(), z.null()]).optional(),
        pl_thumbs: z.union([z.string(), z.null()]).optional(),
        portrait1080: z.union([z.string(), z.null()]).optional(),
        poster400y: z.union([z.string(), z.null()]).optional(),
        potwmedium: z.union([z.string(), z.null()]).optional(),
        publicationjpg: z.union([z.string(), z.null()]).optional(),
        publicationtiff: z.union([z.string(), z.null()]).optional(),
        publicationtiff10k: z.union([z.string(), z.null()]).optional(),
        publicationtiff25k: z.union([z.string(), z.null()]).optional(),
        publicationtiff40k: z.union([z.string(), z.null()]).optional(),
        screen: z.union([z.string(), z.null()]).optional(),
        screen640: z.union([z.string(), z.null()]).optional(),
        thumb150y: z.union([z.string(), z.null()]).optional(),
        thumb300y: z.union([z.string(), z.null()]).optional(),
        thumb350x: z.union([z.string(), z.null()]).optional(),
        thumb700x: z.union([z.string(), z.null()]).optional(),
        thumbs: z.union([z.string(), z.null()]).optional(),
        wallpaper1: z.union([z.string(), z.null()]).optional(),
        wallpaper2: z.union([z.string(), z.null()]).optional(),
        wallpaper3: z.union([z.string(), z.null()]).optional(),
        wallpaper4: z.union([z.string(), z.null()]).optional(),
        wallpaper5: z.union([z.string(), z.null()]).optional(),
        wallpaperthumbs: z.union([z.string(), z.null()]).optional(),
        zoomable: z.union([z.string(), z.null()]).optional(),
      })
      .readonly(),
  }),
});

export const zAuthorDescription = z.object({
  name: z.string().readonly(),
  description: z.string().max(100).optional(),
  photo: z.string().readonly(),
  static_photo: z.string().readonly(),
});

export const zBlankEnum = z.enum([""]);

export const zCategory = z.object({
  slug: z.string(),
  name: z.string().max(255),
  logo_url: z.union([z.string().url().max(255), z.null()]).optional(),
});

export const zImage = z.object({
  id: z
    .string()
    .max(50)
    .regex(/^[-a-zA-Z0-9_]+$/),
  url: z.string().readonly(),
  lang: z.string().max(7).optional(),
  source: z.union([z.string(), z.null()]).optional(),
  title: z.string().max(255),
  headline: z.union([z.string(), z.null()]).optional(),
  description: z.union([z.string(), z.null()]).optional(),
  categories: z.array(zCategory),
  type: z
    .union([
      z.enum([
        "Observation",
        "Artwork",
        "Photographic",
        "Planetary",
        "Simulation",
        "Collage",
        "Chart",
      ]),
      zBlankEnum,
      z.unknown(),
      z.null(),
    ])
    .optional(),
  credit: z.string().optional(),
  release_date: z.string().readonly(),
  width: z
    .union([z.number().int().gte(0).lte(2147483647), z.null()])
    .optional(),
  height: z
    .union([z.number().int().gte(0).lte(2147483647), z.null()])
    .optional(),
  featured: z.boolean().optional(),
  subject_name: z.array(z.string()),
  resources: z
    .array(
      z.object({
        ResourceType: z.string().optional(),
        MediaType: z.string().optional(),
        URL: z.string().optional(),
        FileSize: z.union([z.number().int(), z.null()]).optional(),
        Dimensions: z.union([z.array(z.number().int()), z.null()]).optional(),
        ProjectionType: z.union([z.string(), z.null()]).optional(),
      })
    )
    .readonly(),
  formats: z
    .object({
      banner1920: z.union([z.string(), z.null()]).optional(),
      eps: z.union([z.string(), z.null()]).optional(),
      illustrator: z.union([z.string(), z.null()]).optional(),
      illustrator_text: z.union([z.string(), z.null()]).optional(),
      large: z.union([z.string(), z.null()]).optional(),
      medium: z.union([z.string(), z.null()]).optional(),
      news: z.union([z.string(), z.null()]).optional(),
      newsfeature: z.union([z.string(), z.null()]).optional(),
      newsmini: z.union([z.string(), z.null()]).optional(),
      original: z.union([z.string(), z.null()]).optional(),
      pdf: z.union([z.string(), z.null()]).optional(),
      pl_original: z.union([z.string(), z.null()]).optional(),
      pl_screen: z.union([z.string(), z.null()]).optional(),
      pl_thumbs: z.union([z.string(), z.null()]).optional(),
      portrait1080: z.union([z.string(), z.null()]).optional(),
      poster400y: z.union([z.string(), z.null()]).optional(),
      potwmedium: z.union([z.string(), z.null()]).optional(),
      publicationjpg: z.union([z.string(), z.null()]).optional(),
      publicationtiff: z.union([z.string(), z.null()]).optional(),
      publicationtiff10k: z.union([z.string(), z.null()]).optional(),
      publicationtiff25k: z.union([z.string(), z.null()]).optional(),
      publicationtiff40k: z.union([z.string(), z.null()]).optional(),
      screen: z.union([z.string(), z.null()]).optional(),
      screen640: z.union([z.string(), z.null()]).optional(),
      thumb150y: z.union([z.string(), z.null()]).optional(),
      thumb300y: z.union([z.string(), z.null()]).optional(),
      thumb350x: z.union([z.string(), z.null()]).optional(),
      thumb700x: z.union([z.string(), z.null()]).optional(),
      thumbs: z.union([z.string(), z.null()]).optional(),
      wallpaper1: z.union([z.string(), z.null()]).optional(),
      wallpaper2: z.union([z.string(), z.null()]).optional(),
      wallpaper3: z.union([z.string(), z.null()]).optional(),
      wallpaper4: z.union([z.string(), z.null()]).optional(),
      wallpaper5: z.union([z.string(), z.null()]).optional(),
      wallpaperthumbs: z.union([z.string(), z.null()]).optional(),
      zoomable: z.union([z.string(), z.null()]).optional(),
    })
    .readonly(),
});

export const zImageItem = z.union([
  z.object({
    id: z
      .string()
      .max(50)
      .regex(/^[-a-zA-Z0-9_]+$/),
    url: z.string().readonly(),
    lang: z.string().max(7).optional(),
    source: z.union([z.string(), z.null()]).optional(),
    title: z.string().max(255),
    width: z
      .union([z.number().int().gte(0).lte(2147483647), z.null()])
      .optional(),
    height: z
      .union([z.number().int().gte(0).lte(2147483647), z.null()])
      .optional(),
    formats: z
      .object({
        thumb300y: z.union([z.string(), z.null()]).optional(),
        screen: z.union([z.string(), z.null()]).optional(),
        thumb700x: z.union([z.string(), z.null()]).optional(),
      })
      .readonly(),
  }),
  z.object({
    id: z
      .string()
      .max(50)
      .regex(/^[-a-zA-Z0-9_]+$/),
    url: z.string().readonly(),
    lang: z.string().max(7).optional(),
    source: z.union([z.string(), z.null()]).optional(),
    title: z.string().max(255),
    width: z
      .union([z.number().int().gte(0).lte(2147483647), z.null()])
      .optional(),
    height: z
      .union([z.number().int().gte(0).lte(2147483647), z.null()])
      .optional(),
    featured: z.boolean().optional(),
    categories: z.array(zCategory),
    formats: z
      .object({
        banner1920: z.union([z.string(), z.null()]).optional(),
        eps: z.union([z.string(), z.null()]).optional(),
        illustrator: z.union([z.string(), z.null()]).optional(),
        illustrator_text: z.union([z.string(), z.null()]).optional(),
        large: z.union([z.string(), z.null()]).optional(),
        medium: z.union([z.string(), z.null()]).optional(),
        news: z.union([z.string(), z.null()]).optional(),
        newsfeature: z.union([z.string(), z.null()]).optional(),
        newsmini: z.union([z.string(), z.null()]).optional(),
        original: z.union([z.string(), z.null()]).optional(),
        pdf: z.union([z.string(), z.null()]).optional(),
        pl_original: z.union([z.string(), z.null()]).optional(),
        pl_screen: z.union([z.string(), z.null()]).optional(),
        pl_thumbs: z.union([z.string(), z.null()]).optional(),
        portrait1080: z.union([z.string(), z.null()]).optional(),
        poster400y: z.union([z.string(), z.null()]).optional(),
        potwmedium: z.union([z.string(), z.null()]).optional(),
        publicationjpg: z.union([z.string(), z.null()]).optional(),
        publicationtiff: z.union([z.string(), z.null()]).optional(),
        publicationtiff10k: z.union([z.string(), z.null()]).optional(),
        publicationtiff25k: z.union([z.string(), z.null()]).optional(),
        publicationtiff40k: z.union([z.string(), z.null()]).optional(),
        screen: z.union([z.string(), z.null()]).optional(),
        screen640: z.union([z.string(), z.null()]).optional(),
        thumb150y: z.union([z.string(), z.null()]).optional(),
        thumb300y: z.union([z.string(), z.null()]).optional(),
        thumb350x: z.union([z.string(), z.null()]).optional(),
        thumb700x: z.union([z.string(), z.null()]).optional(),
        thumbs: z.union([z.string(), z.null()]).optional(),
        wallpaper1: z.union([z.string(), z.null()]).optional(),
        wallpaper2: z.union([z.string(), z.null()]).optional(),
        wallpaper3: z.union([z.string(), z.null()]).optional(),
        wallpaper4: z.union([z.string(), z.null()]).optional(),
        wallpaper5: z.union([z.string(), z.null()]).optional(),
        wallpaperthumbs: z.union([z.string(), z.null()]).optional(),
        zoomable: z.union([z.string(), z.null()]).optional(),
      })
      .readonly(),
  }),
]);

export const zImageMini = z.object({
  id: z
    .string()
    .max(50)
    .regex(/^[-a-zA-Z0-9_]+$/),
  url: z.string().readonly(),
  lang: z.string().max(7).optional(),
  source: z.union([z.string(), z.null()]).optional(),
  title: z.string().max(255),
  width: z
    .union([z.number().int().gte(0).lte(2147483647), z.null()])
    .optional(),
  height: z
    .union([z.number().int().gte(0).lte(2147483647), z.null()])
    .optional(),
  featured: z.boolean().optional(),
  categories: z.array(zCategory),
  formats: z
    .object({
      banner1920: z.union([z.string(), z.null()]).optional(),
      eps: z.union([z.string(), z.null()]).optional(),
      illustrator: z.union([z.string(), z.null()]).optional(),
      illustrator_text: z.union([z.string(), z.null()]).optional(),
      large: z.union([z.string(), z.null()]).optional(),
      medium: z.union([z.string(), z.null()]).optional(),
      news: z.union([z.string(), z.null()]).optional(),
      newsfeature: z.union([z.string(), z.null()]).optional(),
      newsmini: z.union([z.string(), z.null()]).optional(),
      original: z.union([z.string(), z.null()]).optional(),
      pdf: z.union([z.string(), z.null()]).optional(),
      pl_original: z.union([z.string(), z.null()]).optional(),
      pl_screen: z.union([z.string(), z.null()]).optional(),
      pl_thumbs: z.union([z.string(), z.null()]).optional(),
      portrait1080: z.union([z.string(), z.null()]).optional(),
      poster400y: z.union([z.string(), z.null()]).optional(),
      potwmedium: z.union([z.string(), z.null()]).optional(),
      publicationjpg: z.union([z.string(), z.null()]).optional(),
      publicationtiff: z.union([z.string(), z.null()]).optional(),
      publicationtiff10k: z.union([z.string(), z.null()]).optional(),
      publicationtiff25k: z.union([z.string(), z.null()]).optional(),
      publicationtiff40k: z.union([z.string(), z.null()]).optional(),
      screen: z.union([z.string(), z.null()]).optional(),
      screen640: z.union([z.string(), z.null()]).optional(),
      thumb150y: z.union([z.string(), z.null()]).optional(),
      thumb300y: z.union([z.string(), z.null()]).optional(),
      thumb350x: z.union([z.string(), z.null()]).optional(),
      thumb700x: z.union([z.string(), z.null()]).optional(),
      thumbs: z.union([z.string(), z.null()]).optional(),
      wallpaper1: z.union([z.string(), z.null()]).optional(),
      wallpaper2: z.union([z.string(), z.null()]).optional(),
      wallpaper3: z.union([z.string(), z.null()]).optional(),
      wallpaper4: z.union([z.string(), z.null()]).optional(),
      wallpaper5: z.union([z.string(), z.null()]).optional(),
      wallpaperthumbs: z.union([z.string(), z.null()]).optional(),
      zoomable: z.union([z.string(), z.null()]).optional(),
    })
    .readonly(),
});

export const zImageTiny = z.object({
  id: z
    .string()
    .max(50)
    .regex(/^[-a-zA-Z0-9_]+$/),
  url: z.string().readonly(),
  lang: z.string().max(7).optional(),
  source: z.union([z.string(), z.null()]).optional(),
  title: z.string().max(255),
  width: z
    .union([z.number().int().gte(0).lte(2147483647), z.null()])
    .optional(),
  height: z
    .union([z.number().int().gte(0).lte(2147483647), z.null()])
    .optional(),
  formats: z
    .object({
      thumb300y: z.union([z.string(), z.null()]).optional(),
      screen: z.union([z.string(), z.null()]).optional(),
      thumb700x: z.union([z.string(), z.null()]).optional(),
    })
    .readonly(),
});

export const zModel3D = z.object({
  id: z
    .string()
    .max(50)
    .regex(/^[-a-zA-Z0-9_]+$/),
  title: z.string().max(200),
  description: z.string().optional(),
  credit: z.string().readonly(),
  priority: z.number().int().gte(0).lte(32767).optional(),
  release_date: z.string().readonly(),
  assets: z.string().readonly(),
});

export const zNullEnum = z.unknown();

export const zPage = z.object({
  title: z.string().max(200),
  content: z.string().optional(),
  description: z.string().optional(),
  keywords: z.string().optional(),
});

export const zPageRequest = z.object({
  title: z.string().min(1).max(200),
  content: z.string().optional(),
  description: z.string().optional(),
  keywords: z.string().optional(),
});

export const zPaginatedAnnouncementMiniList = z.object({
  count: z.number().int().optional(),
  next: z.union([z.string().url(), z.null()]).optional(),
  previous: z.union([z.string().url(), z.null()]).optional(),
  results: z.array(zAnnouncementMini).optional(),
});

export const zPaginatedImageItemList = z.object({
  count: z.number().int().optional(),
  next: z.union([z.string().url(), z.null()]).optional(),
  previous: z.union([z.string().url(), z.null()]).optional(),
  results: z.array(zImageItem).optional(),
});

export const zPaginatedImageList = z.object({
  count: z.number().int().optional(),
  next: z.union([z.string().url(), z.null()]).optional(),
  previous: z.union([z.string().url(), z.null()]).optional(),
  results: z.array(zImage).optional(),
});

export const zPaginatedModel3dList = z.object({
  count: z.number().int().optional(),
  next: z.union([z.string().url(), z.null()]).optional(),
  previous: z.union([z.string().url(), z.null()]).optional(),
  results: z.array(zModel3D).optional(),
});

export const zPaginatedPodcastList = z.object({
  count: z.number().int().optional(),
  next: z.union([z.string().url(), z.null()]).optional(),
  previous: z.union([z.string().url(), z.null()]).optional(),
  results: z
    .array(
      z.object({
        id: z
          .string()
          .max(50)
          .regex(/^[-a-zA-Z0-9_]+$/),
        title: z.string().max(200),
        description: z.string().optional(),
        credit: z.string().readonly(),
        priority: z.number().int().gte(0).lte(32767).optional(),
        release_date: z.string().readonly(),
        assets: z.string().readonly(),
      })
    )
    .optional(),
});

export const zPaginatedReleaseMiniList = z.object({
  count: z.number().int().optional(),
  next: z.union([z.string().url(), z.null()]).optional(),
  previous: z.union([z.string().url(), z.null()]).optional(),
  results: z
    .array(
      z.object({
        id: z
          .string()
          .max(50)
          .regex(/^[-a-zA-Z0-9_]+$/),
        lang: z.string().max(7).optional(),
        url: z.string().readonly(),
        release_type: z.string().readonly(),
        title: z.string().max(255),
        subtitle: z.string().max(255).optional(),
        headline: z.string().optional(),
        release_date: z.string().readonly(),
        programs: z.array(
          z.object({
            slug: z.string(),
            name: z.string().max(255),
            logo_url: z.union([z.string().url().max(255), z.null()]).optional(),
          })
        ),
        main_image: zImageMini,
      })
    )
    .optional(),
});

export const zPaginatedVideoList = z.object({
  count: z.number().int().optional(),
  next: z.union([z.string().url(), z.null()]).optional(),
  previous: z.union([z.string().url(), z.null()]).optional(),
  results: z
    .array(
      z.object({
        id: z
          .string()
          .max(50)
          .regex(/^[-a-zA-Z0-9_]+$/),
        url: z.string().readonly(),
        lang: z.string().max(7).optional(),
        source: z.union([z.string(), z.null()]).optional(),
        title: z.string().max(255),
        headline: z.union([z.string(), z.null()]).optional(),
        description: z.union([z.string(), z.null()]).optional(),
        categories: z.array(zCategory),
        type: z
          .union([
            z.enum([
              "Observation",
              "Artwork",
              "Photographic",
              "Planetary",
              "Simulation",
              "Collage",
              "Chart",
            ]),
            zBlankEnum,
            zNullEnum,
            z.null(),
          ])
          .optional(),
        credit: z.string().optional(),
        release_date: z.string().readonly(),
        featured: z.boolean().optional(),
        duration: z.union([z.string().readonly(), z.null()]).readonly(),
        youtube_video_id: z.union([z.string().max(11), z.null()]).optional(),
        use_youtube: z.boolean().optional(),
        formats: z
          .object({
            broadcast_sd: z.union([z.string(), z.null()]).optional(),
            cylindrical_16kmaster: z.union([z.string(), z.null()]).optional(),
            cylindrical_4kmaster: z.union([z.string(), z.null()]).optional(),
            cylindrical_8kmaster: z.union([z.string(), z.null()]).optional(),
            cylindrical_preview: z.union([z.string(), z.null()]).optional(),
            dome_2kmaster: z.union([z.string(), z.null()]).optional(),
            dome_2kplayback: z.union([z.string(), z.null()]).optional(),
            dome_4kmaster: z.union([z.string(), z.null()]).optional(),
            dome_4kplayback: z.union([z.string(), z.null()]).optional(),
            dome_8kmaster: z.union([z.string(), z.null()]).optional(),
            dome_mov: z.union([z.string(), z.null()]).optional(),
            dome_preview: z.union([z.string(), z.null()]).optional(),
            ext_highres: z.union([z.string(), z.null()]).optional(),
            ext_playback: z.union([z.string(), z.null()]).optional(),
            hd_1080_broadcast: z.union([z.string(), z.null()]).optional(),
            hd_1080_screen: z.union([z.string(), z.null()]).optional(),
            hd_1080p25_broadcast: z.union([z.string(), z.null()]).optional(),
            hd_1080p25_screen: z.union([z.string(), z.null()]).optional(),
            hd_and_apple: z.union([z.string(), z.null()]).optional(),
            hd_broadcast_720p25: z.union([z.string(), z.null()]).optional(),
            hd_broadcast_720p50: z.union([z.string(), z.null()]).optional(),
            large_qt: z.union([z.string(), z.null()]).optional(),
            medium_flash: z.union([z.string(), z.null()]).optional(),
            medium_mpeg1: z.union([z.string(), z.null()]).optional(),
            medium_podcast: z.union([z.string(), z.null()]).optional(),
            news: z.union([z.string(), z.null()]).optional(),
            newsfeature: z.union([z.string(), z.null()]).optional(),
            newsmini: z.union([z.string(), z.null()]).optional(),
            old_video: z.union([z.string(), z.null()]).optional(),
            original: z.union([z.string(), z.null()]).optional(),
            potwmedium: z.union([z.string(), z.null()]).optional(),
            qtvr: z.union([z.string(), z.null()]).optional(),
            script: z.union([z.string(), z.null()]).optional(),
            small_flash: z.union([z.string(), z.null()]).optional(),
            small_qt: z.union([z.string(), z.null()]).optional(),
            thumb: z.union([z.string(), z.null()]).optional(),
            thumb300y: z.union([z.string(), z.null()]).optional(),
            thumb350x: z.union([z.string(), z.null()]).optional(),
            ultra_hd: z.union([z.string(), z.null()]).optional(),
            ultra_hd_8k_broadcast: z.union([z.string(), z.null()]).optional(),
            ultra_hd_8k_h265: z.union([z.string(), z.null()]).optional(),
            ultra_hd_broadcast: z.union([z.string(), z.null()]).optional(),
            ultra_hd_h265: z.union([z.string(), z.null()]).optional(),
            videoframe: z.union([z.string(), z.null()]).optional(),
            vr_16kmaster: z.union([z.string(), z.null()]).optional(),
            vr_2k_sos: z.union([z.string(), z.null()]).optional(),
            vr_4k: z.union([z.string(), z.null()]).optional(),
            vr_4k_sos: z.union([z.string(), z.null()]).optional(),
            vr_4kmaster: z.union([z.string(), z.null()]).optional(),
            vr_8k: z.union([z.string(), z.null()]).optional(),
            vr_8kmaster: z.union([z.string(), z.null()]).optional(),
          })
          .readonly(),
      })
    )
    .optional(),
});

export const zPaginatedVideoMiniList = z.object({
  count: z.number().int().optional(),
  next: z.union([z.string().url(), z.null()]).optional(),
  previous: z.union([z.string().url(), z.null()]).optional(),
  results: z
    .array(
      z.object({
        id: z
          .string()
          .max(50)
          .regex(/^[-a-zA-Z0-9_]+$/),
        url: z.string().readonly(),
        lang: z.string().max(7).optional(),
        source: z.union([z.string(), z.null()]).optional(),
        title: z.string().max(255),
        featured: z.boolean().optional(),
        duration: z.union([z.string().readonly(), z.null()]).readonly(),
        categories: z.array(zCategory),
        youtube_video_id: z.union([z.string().max(11), z.null()]).optional(),
        use_youtube: z.boolean().optional(),
        formats: z
          .object({
            broadcast_sd: z.union([z.string(), z.null()]).optional(),
            cylindrical_16kmaster: z.union([z.string(), z.null()]).optional(),
            cylindrical_4kmaster: z.union([z.string(), z.null()]).optional(),
            cylindrical_8kmaster: z.union([z.string(), z.null()]).optional(),
            cylindrical_preview: z.union([z.string(), z.null()]).optional(),
            dome_2kmaster: z.union([z.string(), z.null()]).optional(),
            dome_2kplayback: z.union([z.string(), z.null()]).optional(),
            dome_4kmaster: z.union([z.string(), z.null()]).optional(),
            dome_4kplayback: z.union([z.string(), z.null()]).optional(),
            dome_8kmaster: z.union([z.string(), z.null()]).optional(),
            dome_mov: z.union([z.string(), z.null()]).optional(),
            dome_preview: z.union([z.string(), z.null()]).optional(),
            ext_highres: z.union([z.string(), z.null()]).optional(),
            ext_playback: z.union([z.string(), z.null()]).optional(),
            hd_1080_broadcast: z.union([z.string(), z.null()]).optional(),
            hd_1080_screen: z.union([z.string(), z.null()]).optional(),
            hd_1080p25_broadcast: z.union([z.string(), z.null()]).optional(),
            hd_1080p25_screen: z.union([z.string(), z.null()]).optional(),
            hd_and_apple: z.union([z.string(), z.null()]).optional(),
            hd_broadcast_720p25: z.union([z.string(), z.null()]).optional(),
            hd_broadcast_720p50: z.union([z.string(), z.null()]).optional(),
            large_qt: z.union([z.string(), z.null()]).optional(),
            medium_flash: z.union([z.string(), z.null()]).optional(),
            medium_mpeg1: z.union([z.string(), z.null()]).optional(),
            medium_podcast: z.union([z.string(), z.null()]).optional(),
            news: z.union([z.string(), z.null()]).optional(),
            newsfeature: z.union([z.string(), z.null()]).optional(),
            newsmini: z.union([z.string(), z.null()]).optional(),
            old_video: z.union([z.string(), z.null()]).optional(),
            original: z.union([z.string(), z.null()]).optional(),
            potwmedium: z.union([z.string(), z.null()]).optional(),
            qtvr: z.union([z.string(), z.null()]).optional(),
            script: z.union([z.string(), z.null()]).optional(),
            small_flash: z.union([z.string(), z.null()]).optional(),
            small_qt: z.union([z.string(), z.null()]).optional(),
            thumb: z.union([z.string(), z.null()]).optional(),
            thumb300y: z.union([z.string(), z.null()]).optional(),
            thumb350x: z.union([z.string(), z.null()]).optional(),
            ultra_hd: z.union([z.string(), z.null()]).optional(),
            ultra_hd_8k_broadcast: z.union([z.string(), z.null()]).optional(),
            ultra_hd_8k_h265: z.union([z.string(), z.null()]).optional(),
            ultra_hd_broadcast: z.union([z.string(), z.null()]).optional(),
            ultra_hd_h265: z.union([z.string(), z.null()]).optional(),
            videoframe: z.union([z.string(), z.null()]).optional(),
            vr_16kmaster: z.union([z.string(), z.null()]).optional(),
            vr_2k_sos: z.union([z.string(), z.null()]).optional(),
            vr_4k: z.union([z.string(), z.null()]).optional(),
            vr_4k_sos: z.union([z.string(), z.null()]).optional(),
            vr_4kmaster: z.union([z.string(), z.null()]).optional(),
            vr_8k: z.union([z.string(), z.null()]).optional(),
            vr_8kmaster: z.union([z.string(), z.null()]).optional(),
          })
          .readonly(),
      })
    )
    .optional(),
});

export const zPatchedPageRequest = z.object({
  title: z.string().min(1).max(200).optional(),
  content: z.string().optional(),
  description: z.string().optional(),
  keywords: z.string().optional(),
});

export const zPodcast = z.object({
  id: z
    .string()
    .max(50)
    .regex(/^[-a-zA-Z0-9_]+$/),
  title: z.string().max(200),
  description: z.string().optional(),
  credit: z.string().readonly(),
  priority: z.number().int().gte(0).lte(32767).optional(),
  release_date: z.string().readonly(),
  assets: z.string().readonly(),
});

export const zPost = z.object({
  id: z.string().readonly(),
  slug: z
    .string()
    .max(50)
    .regex(/^[-a-zA-Z0-9_]+$/),
  url: z.string().readonly(),
  title: z.string().max(255),
  subtitle: z.string().max(255).optional(),
  banner: z.string().readonly(),
  authors: z.array(zAuthorDescription),
  category: zCategory,
  lede: z.string(),
  release_date: z.union([z.string().datetime(), z.null()]).optional(),
});

export const zProgram = z.object({
  slug: z.string(),
  name: z.string().max(255),
  logo_url: z.union([z.string().url().max(255), z.null()]).optional(),
});

export const zRelease = z.object({
  id: z
    .string()
    .max(50)
    .regex(/^[-a-zA-Z0-9_]+$/),
  lang: z.string().max(7).optional(),
  url: z.string().readonly(),
  title: z.string().max(255),
  release_type: z.string().readonly(),
  subtitle: z.string().max(255).optional(),
  headline: z.string().optional(),
  release_date: z.string().readonly(),
  description: z.string().optional(),
  notes: z.string().optional(),
  more_information: z.string().optional(),
  links: z.string().optional(),
  disclaimer: z.string().optional(),
  programs: z.array(zProgram),
  images: z.array(zImageMini).readonly(),
  videos: z
    .array(
      z.object({
        id: z
          .string()
          .max(50)
          .regex(/^[-a-zA-Z0-9_]+$/),
        url: z.string().readonly(),
        lang: z.string().max(7).optional(),
        source: z.union([z.string(), z.null()]).optional(),
        title: z.string().max(255),
        featured: z.boolean().optional(),
        duration: z.union([z.string().readonly(), z.null()]).readonly(),
        categories: z.array(zCategory),
        youtube_video_id: z.union([z.string().max(11), z.null()]).optional(),
        use_youtube: z.boolean().optional(),
        formats: z
          .object({
            broadcast_sd: z.union([z.string(), z.null()]).optional(),
            cylindrical_16kmaster: z.union([z.string(), z.null()]).optional(),
            cylindrical_4kmaster: z.union([z.string(), z.null()]).optional(),
            cylindrical_8kmaster: z.union([z.string(), z.null()]).optional(),
            cylindrical_preview: z.union([z.string(), z.null()]).optional(),
            dome_2kmaster: z.union([z.string(), z.null()]).optional(),
            dome_2kplayback: z.union([z.string(), z.null()]).optional(),
            dome_4kmaster: z.union([z.string(), z.null()]).optional(),
            dome_4kplayback: z.union([z.string(), z.null()]).optional(),
            dome_8kmaster: z.union([z.string(), z.null()]).optional(),
            dome_mov: z.union([z.string(), z.null()]).optional(),
            dome_preview: z.union([z.string(), z.null()]).optional(),
            ext_highres: z.union([z.string(), z.null()]).optional(),
            ext_playback: z.union([z.string(), z.null()]).optional(),
            hd_1080_broadcast: z.union([z.string(), z.null()]).optional(),
            hd_1080_screen: z.union([z.string(), z.null()]).optional(),
            hd_1080p25_broadcast: z.union([z.string(), z.null()]).optional(),
            hd_1080p25_screen: z.union([z.string(), z.null()]).optional(),
            hd_and_apple: z.union([z.string(), z.null()]).optional(),
            hd_broadcast_720p25: z.union([z.string(), z.null()]).optional(),
            hd_broadcast_720p50: z.union([z.string(), z.null()]).optional(),
            large_qt: z.union([z.string(), z.null()]).optional(),
            medium_flash: z.union([z.string(), z.null()]).optional(),
            medium_mpeg1: z.union([z.string(), z.null()]).optional(),
            medium_podcast: z.union([z.string(), z.null()]).optional(),
            news: z.union([z.string(), z.null()]).optional(),
            newsfeature: z.union([z.string(), z.null()]).optional(),
            newsmini: z.union([z.string(), z.null()]).optional(),
            old_video: z.union([z.string(), z.null()]).optional(),
            original: z.union([z.string(), z.null()]).optional(),
            potwmedium: z.union([z.string(), z.null()]).optional(),
            qtvr: z.union([z.string(), z.null()]).optional(),
            script: z.union([z.string(), z.null()]).optional(),
            small_flash: z.union([z.string(), z.null()]).optional(),
            small_qt: z.union([z.string(), z.null()]).optional(),
            thumb: z.union([z.string(), z.null()]).optional(),
            thumb300y: z.union([z.string(), z.null()]).optional(),
            thumb350x: z.union([z.string(), z.null()]).optional(),
            ultra_hd: z.union([z.string(), z.null()]).optional(),
            ultra_hd_8k_broadcast: z.union([z.string(), z.null()]).optional(),
            ultra_hd_8k_h265: z.union([z.string(), z.null()]).optional(),
            ultra_hd_broadcast: z.union([z.string(), z.null()]).optional(),
            ultra_hd_h265: z.union([z.string(), z.null()]).optional(),
            videoframe: z.union([z.string(), z.null()]).optional(),
            vr_16kmaster: z.union([z.string(), z.null()]).optional(),
            vr_2k_sos: z.union([z.string(), z.null()]).optional(),
            vr_4k: z.union([z.string(), z.null()]).optional(),
            vr_4k_sos: z.union([z.string(), z.null()]).optional(),
            vr_4kmaster: z.union([z.string(), z.null()]).optional(),
            vr_8k: z.union([z.string(), z.null()]).optional(),
            vr_8kmaster: z.union([z.string(), z.null()]).optional(),
          })
          .readonly(),
      })
    )
    .readonly(),
  contacts: z.array(
    z.object({
      name: z.string().max(255).optional(),
      email: z.string().max(255).optional(),
      telephone: z.string().max(255).optional(),
      cellular: z.string().max(255).optional(),
      affiliation: z.string().max(255).optional(),
      address: z.string().max(255).optional(),
      city: z.string().max(255).optional(),
      state_province: z.string().max(255).optional(),
      postal_code: z.string().max(255).optional(),
      country: z.string().max(255).optional(),
    })
  ),
});

export const zReleaseContact = z.object({
  name: z.string().max(255).optional(),
  email: z.string().max(255).optional(),
  telephone: z.string().max(255).optional(),
  cellular: z.string().max(255).optional(),
  affiliation: z.string().max(255).optional(),
  address: z.string().max(255).optional(),
  city: z.string().max(255).optional(),
  state_province: z.string().max(255).optional(),
  postal_code: z.string().max(255).optional(),
  country: z.string().max(255).optional(),
});

export const zReleaseMini = z.object({
  id: z
    .string()
    .max(50)
    .regex(/^[-a-zA-Z0-9_]+$/),
  lang: z.string().max(7).optional(),
  url: z.string().readonly(),
  release_type: z.string().readonly(),
  title: z.string().max(255),
  subtitle: z.string().max(255).optional(),
  headline: z.string().optional(),
  release_date: z.string().readonly(),
  programs: z.array(zProgram),
  main_image: zImageMini,
});

export const zShowing = z.object({
  id: z.number().int().readonly(),
  start_time: z.string().readonly(),
  formatted_start_time: z.string().readonly(),
  free_spaces: z.number().int(),
});

export const zTypeEnum = z.enum([
  "Observation",
  "Artwork",
  "Photographic",
  "Planetary",
  "Simulation",
  "Collage",
  "Chart",
]);

export const zVideo = z.object({
  id: z
    .string()
    .max(50)
    .regex(/^[-a-zA-Z0-9_]+$/),
  url: z.string().readonly(),
  lang: z.string().max(7).optional(),
  source: z.union([z.string(), z.null()]).optional(),
  title: z.string().max(255),
  headline: z.union([z.string(), z.null()]).optional(),
  description: z.union([z.string(), z.null()]).optional(),
  categories: z.array(zCategory),
  type: z.union([zTypeEnum, zBlankEnum, zNullEnum, z.null()]).optional(),
  credit: z.string().optional(),
  release_date: z.string().readonly(),
  featured: z.boolean().optional(),
  duration: z.union([z.string().readonly(), z.null()]).readonly(),
  youtube_video_id: z.union([z.string().max(11), z.null()]).optional(),
  use_youtube: z.boolean().optional(),
  formats: z
    .object({
      broadcast_sd: z.union([z.string(), z.null()]).optional(),
      cylindrical_16kmaster: z.union([z.string(), z.null()]).optional(),
      cylindrical_4kmaster: z.union([z.string(), z.null()]).optional(),
      cylindrical_8kmaster: z.union([z.string(), z.null()]).optional(),
      cylindrical_preview: z.union([z.string(), z.null()]).optional(),
      dome_2kmaster: z.union([z.string(), z.null()]).optional(),
      dome_2kplayback: z.union([z.string(), z.null()]).optional(),
      dome_4kmaster: z.union([z.string(), z.null()]).optional(),
      dome_4kplayback: z.union([z.string(), z.null()]).optional(),
      dome_8kmaster: z.union([z.string(), z.null()]).optional(),
      dome_mov: z.union([z.string(), z.null()]).optional(),
      dome_preview: z.union([z.string(), z.null()]).optional(),
      ext_highres: z.union([z.string(), z.null()]).optional(),
      ext_playback: z.union([z.string(), z.null()]).optional(),
      hd_1080_broadcast: z.union([z.string(), z.null()]).optional(),
      hd_1080_screen: z.union([z.string(), z.null()]).optional(),
      hd_1080p25_broadcast: z.union([z.string(), z.null()]).optional(),
      hd_1080p25_screen: z.union([z.string(), z.null()]).optional(),
      hd_and_apple: z.union([z.string(), z.null()]).optional(),
      hd_broadcast_720p25: z.union([z.string(), z.null()]).optional(),
      hd_broadcast_720p50: z.union([z.string(), z.null()]).optional(),
      large_qt: z.union([z.string(), z.null()]).optional(),
      medium_flash: z.union([z.string(), z.null()]).optional(),
      medium_mpeg1: z.union([z.string(), z.null()]).optional(),
      medium_podcast: z.union([z.string(), z.null()]).optional(),
      news: z.union([z.string(), z.null()]).optional(),
      newsfeature: z.union([z.string(), z.null()]).optional(),
      newsmini: z.union([z.string(), z.null()]).optional(),
      old_video: z.union([z.string(), z.null()]).optional(),
      original: z.union([z.string(), z.null()]).optional(),
      potwmedium: z.union([z.string(), z.null()]).optional(),
      qtvr: z.union([z.string(), z.null()]).optional(),
      script: z.union([z.string(), z.null()]).optional(),
      small_flash: z.union([z.string(), z.null()]).optional(),
      small_qt: z.union([z.string(), z.null()]).optional(),
      thumb: z.union([z.string(), z.null()]).optional(),
      thumb300y: z.union([z.string(), z.null()]).optional(),
      thumb350x: z.union([z.string(), z.null()]).optional(),
      ultra_hd: z.union([z.string(), z.null()]).optional(),
      ultra_hd_8k_broadcast: z.union([z.string(), z.null()]).optional(),
      ultra_hd_8k_h265: z.union([z.string(), z.null()]).optional(),
      ultra_hd_broadcast: z.union([z.string(), z.null()]).optional(),
      ultra_hd_h265: z.union([z.string(), z.null()]).optional(),
      videoframe: z.union([z.string(), z.null()]).optional(),
      vr_16kmaster: z.union([z.string(), z.null()]).optional(),
      vr_2k_sos: z.union([z.string(), z.null()]).optional(),
      vr_4k: z.union([z.string(), z.null()]).optional(),
      vr_4k_sos: z.union([z.string(), z.null()]).optional(),
      vr_4kmaster: z.union([z.string(), z.null()]).optional(),
      vr_8k: z.union([z.string(), z.null()]).optional(),
      vr_8kmaster: z.union([z.string(), z.null()]).optional(),
    })
    .readonly(),
});

export const zVideoMini = z.object({
  id: z
    .string()
    .max(50)
    .regex(/^[-a-zA-Z0-9_]+$/),
  url: z.string().readonly(),
  lang: z.string().max(7).optional(),
  source: z.union([z.string(), z.null()]).optional(),
  title: z.string().max(255),
  featured: z.boolean().optional(),
  duration: z.union([z.string().readonly(), z.null()]).readonly(),
  categories: z.array(zCategory),
  youtube_video_id: z.union([z.string().max(11), z.null()]).optional(),
  use_youtube: z.boolean().optional(),
  formats: z
    .object({
      broadcast_sd: z.union([z.string(), z.null()]).optional(),
      cylindrical_16kmaster: z.union([z.string(), z.null()]).optional(),
      cylindrical_4kmaster: z.union([z.string(), z.null()]).optional(),
      cylindrical_8kmaster: z.union([z.string(), z.null()]).optional(),
      cylindrical_preview: z.union([z.string(), z.null()]).optional(),
      dome_2kmaster: z.union([z.string(), z.null()]).optional(),
      dome_2kplayback: z.union([z.string(), z.null()]).optional(),
      dome_4kmaster: z.union([z.string(), z.null()]).optional(),
      dome_4kplayback: z.union([z.string(), z.null()]).optional(),
      dome_8kmaster: z.union([z.string(), z.null()]).optional(),
      dome_mov: z.union([z.string(), z.null()]).optional(),
      dome_preview: z.union([z.string(), z.null()]).optional(),
      ext_highres: z.union([z.string(), z.null()]).optional(),
      ext_playback: z.union([z.string(), z.null()]).optional(),
      hd_1080_broadcast: z.union([z.string(), z.null()]).optional(),
      hd_1080_screen: z.union([z.string(), z.null()]).optional(),
      hd_1080p25_broadcast: z.union([z.string(), z.null()]).optional(),
      hd_1080p25_screen: z.union([z.string(), z.null()]).optional(),
      hd_and_apple: z.union([z.string(), z.null()]).optional(),
      hd_broadcast_720p25: z.union([z.string(), z.null()]).optional(),
      hd_broadcast_720p50: z.union([z.string(), z.null()]).optional(),
      large_qt: z.union([z.string(), z.null()]).optional(),
      medium_flash: z.union([z.string(), z.null()]).optional(),
      medium_mpeg1: z.union([z.string(), z.null()]).optional(),
      medium_podcast: z.union([z.string(), z.null()]).optional(),
      news: z.union([z.string(), z.null()]).optional(),
      newsfeature: z.union([z.string(), z.null()]).optional(),
      newsmini: z.union([z.string(), z.null()]).optional(),
      old_video: z.union([z.string(), z.null()]).optional(),
      original: z.union([z.string(), z.null()]).optional(),
      potwmedium: z.union([z.string(), z.null()]).optional(),
      qtvr: z.union([z.string(), z.null()]).optional(),
      script: z.union([z.string(), z.null()]).optional(),
      small_flash: z.union([z.string(), z.null()]).optional(),
      small_qt: z.union([z.string(), z.null()]).optional(),
      thumb: z.union([z.string(), z.null()]).optional(),
      thumb300y: z.union([z.string(), z.null()]).optional(),
      thumb350x: z.union([z.string(), z.null()]).optional(),
      ultra_hd: z.union([z.string(), z.null()]).optional(),
      ultra_hd_8k_broadcast: z.union([z.string(), z.null()]).optional(),
      ultra_hd_8k_h265: z.union([z.string(), z.null()]).optional(),
      ultra_hd_broadcast: z.union([z.string(), z.null()]).optional(),
      ultra_hd_h265: z.union([z.string(), z.null()]).optional(),
      videoframe: z.union([z.string(), z.null()]).optional(),
      vr_16kmaster: z.union([z.string(), z.null()]).optional(),
      vr_2k_sos: z.union([z.string(), z.null()]).optional(),
      vr_4k: z.union([z.string(), z.null()]).optional(),
      vr_4k_sos: z.union([z.string(), z.null()]).optional(),
      vr_4kmaster: z.union([z.string(), z.null()]).optional(),
      vr_8k: z.union([z.string(), z.null()]).optional(),
      vr_8kmaster: z.union([z.string(), z.null()]).optional(),
    })
    .readonly(),
});

export const zAnnouncementsListResponse = zPaginatedAnnouncementMiniList;

export const zAnnouncementsRetrieveResponse = zAnnouncement;

export const zMediaImagesListResponse = zPaginatedImageItemList;

export const zMediaImagesRetrieveResponse = zImage;

export const zMediaVideosListResponse = zPaginatedVideoMiniList;

export const zMediaVideosRetrieveResponse = zVideo;

export const zReleasesListResponse = zPaginatedReleaseMiniList;

export const zReleasesRetrieveResponse = zRelease;

export const zVisitsActivitiesRetrieveResponse = zActivity;

export const zVisitsShowingsListResponse = z.array(zShowing);

export const zBlogApiPostsListResponse = z.array(zPost);

export const zCommunicationPagesApiCommitteeListResponse = z.array(zPage);

export const zCommunicationPagesApiCommitteeCreateResponse = zPage;

export const zCommunicationPagesApiCommitteeDestroyResponse = z.void();

export const zCommunicationPagesApiCommitteeRetrieveResponse = zPage;

export const zCommunicationPagesApiCommitteePartialUpdateResponse = zPage;

export const zCommunicationPagesApiCommitteeUpdateResponse = zPage;

export const zDjangoplicityAdminPagesApiPagesListResponse = z.array(zPage);

export const zDjangoplicityAdminPagesApiPagesCreateResponse = zPage;

export const zDjangoplicityAdminPagesApiPagesDestroyResponse = z.void();

export const zDjangoplicityAdminPagesApiPagesRetrieveResponse = zPage;

export const zDjangoplicityAdminPagesApiPagesPartialUpdateResponse = zPage;

export const zDjangoplicityAdminPagesApiPagesUpdateResponse = zPage;

export const zDocumentationSchemaRetrieveResponse = z.object({});

export const zImagesD2dListResponse = zPaginatedImageList;

export const zProductsModels3dD2dListResponse = zPaginatedModel3dList;

export const zProductsPodcastD2dListResponse = zPaginatedPodcastList;

export const zVideosD2dListResponse = zPaginatedVideoList;
