fragment CantoAssetMetadata on CantoDamAssetInterface {
  additional {
    AltTextEN
    AltTextES
    TitleEN
    TitleES
    CaptionEN
    CaptionES
    Credit
  }
  height
  id
  name
  scheme
  url {
    directUrlOriginal
    directUrlPreview
    directUrlPreviewPlay
  }
  width
}
