fragment calloutBlock on contentBlocks_callout_BlockType {
  id
  typeHandle
  callout {
    ...CalloutMain
    ... on callouts_calloutTwoTone_Entry {
      backgroundColor
      backgroundImage: cantoAssetSingle {
        ...CantoAssetSingle
      }
      captionRichText
      header
      image: contentImage {
        ... on contentImages_Asset {
          altText
          width
          height
          url @transform(mode: "crop", width: 800, height: 550)
        }
      }
      links {
        ...LinksFragment
      }
      text
      calloutType: typeHandle
    }
    ... on callouts_calloutQuote_Entry {
      calloutType: typeHandle
      header
      text
      colorScheme
      links {
        ...LinksFragment
      }
      quote
      attribution
      imageQuote {
        ... on contentImages_Asset {
          altText
          width
          height
          url @transform(mode: "crop", width: 492, height: 492)
        }
      }
    }
    ...CalloutNews
    ...CalloutEvent
  }
}
