fragment keyNumbersBlock on contentBlocks_keyNumbersGrid_BlockType {
  id
  typeHandle
  header
  backgroundColor
  fullWidth
  keyNumbers: children {
    ... on contentBlocks_keyNumbersGridItem_BlockType {
      header
      footer
      id
      postscript
      subheading
    }
  }
  mixedLink {
    ...MixedLinkFragment
  }
}
