fragment newsBlock on contentBlocks_news_BlockType {
  id
  header
  mixedLink {
    customText
    text
    title
    type
    url
    element {
      uri
    }
  }
  postType {
    id
    title
    slug
  }
  numberOfItems
  typeHandle
  items: children {
    ... on contentBlocks_newsItem_BlockType {
      entry: newsEntry {
        id
        title
        uri
        ... on news_post_Entry {
          description: teaser
          hero {
            ... on heroes_Asset {
              altText
              width
              height
              url @transform(mode: "crop", width: 900, height: 550)
            }
          }
          image: hero {
            ... on heroes_Asset {
              altText
              width
              height
              url @transform(mode: "crop", width: 900, height: 550)
            }
          }
        }
      }
    }
  }
}
