fragment summitStatusCompactViewBlock on contentBlocks_summitStatusCompactView_BlockType {
  id
  typeHandle
  showWeatherCondition
  weatherConditionTooltipText
  showAllSkyImage
  allSkyImageTooltipText
  showDomeStatus
  domeStatusTooltipText
  showExposureCount
  exposureCountTooltipText
  showAlertCount
  alertCountTooltipText
  showSurveyProgress
  surveyProgressTooltipText
  showSunsetSunriseTimes
  sunsetSunriseTimesTooltipText
  showWildlifeGallerySpotlight
  wildlifeGallery {
    ... on galleries_gallery_Entry {
      slug
      assetAlbum {
        id
        url {
          directUrlOriginal
        }
        additional {
          AltTextEN
          CaptionEN
          Credit
        }
      }
    }
  }
  wildlifeGallerySpotlightTooltipText
  summitStatusDashboardCaption {
    customText
    ariaLabel
    url
    type
    title
    text
    target
  }
}