fragment summitStatusCompactViewBlock on contentBlocks_summitStatusCompactView_BlockType {
  id
  typeHandle
  domeStatus
  alertCount
  allSkyImage
  exposureCount
  surveyProgress
  weatherCondition
}