// This file is auto-generated by @hey-api/openapi-ts

import {
  createClient,
  createConfig,
  type Options,
} from "@hey-api/client-fetch";
import type {
  AnnouncementsListData,
  AnnouncementsListError,
  AnnouncementsListResponse,
  AnnouncementsRetrieveData,
  AnnouncementsRetrieveError,
  AnnouncementsRetrieveResponse,
  MediaImagesListData,
  MediaImagesListError,
  MediaImagesListResponse,
  MediaImagesRetrieveData,
  MediaImagesRetrieveError,
  MediaImagesRetrieveResponse,
  MediaVideosListData,
  MediaVideosListError,
  MediaVideosListResponse,
  MediaVideosRetrieveData,
  MediaVideosRetrieveError,
  MediaVideosRetrieveResponse,
  ReleasesListData,
  ReleasesListError,
  ReleasesListResponse,
  ReleasesRetrieveData,
  ReleasesRetrieveError,
  ReleasesRetrieveResponse,
  VisitsActivitiesRetrieveData,
  VisitsActivitiesRetrieveError,
  VisitsActivitiesRetrieveResponse,
  VisitsShowingsListData,
  VisitsShowingsListError,
  VisitsShowingsListResponse,
} from "./types.gen";

export const client = createClient(createConfig());

export class AnnouncementsService {
  public static announcementsList<ThrowOnError extends boolean = false>(
    options?: Options<AnnouncementsListData, ThrowOnError>
  ) {
    return (options?.client ?? client).get<
      AnnouncementsListResponse,
      AnnouncementsListError,
      ThrowOnError
    >({
      ...options,
      url: "/public/api/v2/announcements/",
    });
  }

  public static announcementsRetrieve<ThrowOnError extends boolean = false>(
    options: Options<AnnouncementsRetrieveData, ThrowOnError>
  ) {
    return (options?.client ?? client).get<
      AnnouncementsRetrieveResponse,
      AnnouncementsRetrieveError,
      ThrowOnError
    >({
      ...options,
      url: "/public/api/v2/announcements/{id}/",
    });
  }
}

export class MediaService {
  public static mediaImagesList<ThrowOnError extends boolean = false>(
    options?: Options<MediaImagesListData, ThrowOnError>
  ) {
    return (options?.client ?? client).get<
      MediaImagesListResponse,
      MediaImagesListError,
      ThrowOnError
    >({
      ...options,
      url: "/public/api/v2/media/images/",
    });
  }

  public static mediaImagesRetrieve<ThrowOnError extends boolean = false>(
    options: Options<MediaImagesRetrieveData, ThrowOnError>
  ) {
    return (options?.client ?? client).get<
      MediaImagesRetrieveResponse,
      MediaImagesRetrieveError,
      ThrowOnError
    >({
      ...options,
      url: "/public/api/v2/media/images/{id}/",
    });
  }

  public static mediaVideosList<ThrowOnError extends boolean = false>(
    options?: Options<MediaVideosListData, ThrowOnError>
  ) {
    return (options?.client ?? client).get<
      MediaVideosListResponse,
      MediaVideosListError,
      ThrowOnError
    >({
      ...options,
      url: "/public/api/v2/media/videos/",
    });
  }

  public static mediaVideosRetrieve<ThrowOnError extends boolean = false>(
    options: Options<MediaVideosRetrieveData, ThrowOnError>
  ) {
    return (options?.client ?? client).get<
      MediaVideosRetrieveResponse,
      MediaVideosRetrieveError,
      ThrowOnError
    >({
      ...options,
      url: "/public/api/v2/media/videos/{id}/",
    });
  }
}

export class ReleasesService {
  public static releasesList<ThrowOnError extends boolean = false>(
    options?: Options<ReleasesListData, ThrowOnError>
  ) {
    return (options?.client ?? client).get<
      ReleasesListResponse,
      ReleasesListError,
      ThrowOnError
    >({
      ...options,
      url: "/public/api/v2/releases/",
    });
  }

  public static releasesRetrieve<ThrowOnError extends boolean = false>(
    options: Options<ReleasesRetrieveData, ThrowOnError>
  ) {
    return (options?.client ?? client).get<
      ReleasesRetrieveResponse,
      ReleasesRetrieveError,
      ThrowOnError
    >({
      ...options,
      url: "/public/api/v2/releases/{id}/",
    });
  }
}

export class VisitsService {
  public static visitsActivitiesRetrieve<ThrowOnError extends boolean = false>(
    options: Options<VisitsActivitiesRetrieveData, ThrowOnError>
  ) {
    return (options?.client ?? client).get<
      VisitsActivitiesRetrieveResponse,
      VisitsActivitiesRetrieveError,
      ThrowOnError
    >({
      ...options,
      url: "/public/api/v2/visits/activities/{id}/",
    });
  }

  public static visitsShowingsList<ThrowOnError extends boolean = false>(
    options?: Options<VisitsShowingsListData, ThrowOnError>
  ) {
    return (options?.client ?? client).get<
      VisitsShowingsListResponse,
      VisitsShowingsListError,
      ThrowOnError
    >({
      ...options,
      url: "/public/api/v2/visits/showings/",
    });
  }
}
