// This file is auto-generated by @hey-api/openapi-ts

import {
  createClient,
  createConfig,
  type Options,
} from "@hey-api/client-fetch";
import type {
  ReleasesListData,
  ReleasesListError,
  ReleasesListResponse,
  ReleasesRetrieveData,
  ReleasesRetrieveError,
  ReleasesRetrieveResponse,
} from "./types.gen";

export const client = createClient(createConfig());

export class ReleasesService {
  public static releasesList<ThrowOnError extends boolean = false>(
    options?: Options<ReleasesListData, ThrowOnError>
  ) {
    return (options?.client ?? client).get<
      ReleasesListResponse,
      ReleasesListError,
      ThrowOnError
    >({
      ...options,
      url: "/public/api/v2/releases/",
    });
  }

  public static releasesRetrieve<ThrowOnError extends boolean = false>(
    options: Options<ReleasesRetrieveData, ThrowOnError>
  ) {
    return (options?.client ?? client).get<
      ReleasesRetrieveResponse,
      ReleasesRetrieveError,
      ThrowOnError
    >({
      ...options,
      url: "/public/api/v2/releases/{id}/",
    });
  }
}
