name: 'Rubin Obs Client PR preview to Dev GAE'

on:
  pull_request:
    types:
      - 'opened'
      - 'synchronize'
      - 'reopened'
      - 'closed'
    branches:
      - 'develop'

jobs:
  build-push-deploy:
    name: 'Build, Publish, and Deploy'
    runs-on: ubuntu-latest
    if: ${{ github.event.action != 'closed'}}

    # Checkout the repository to the GitHub Actions runner
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # gcloud CLI setup
    - name: Login to GCP
      uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.DEV_SA_KEY }}
        project_id: ${{ secrets.SV_PROJ_NAME }}
        export_default_credentials: true
    
    - name: Build Container Image
      run: |-
        docker build \
        -t "gcr.io/${{ secrets.SV_PROJ_NAME }}/rubin-obs-client:${{ github.sha }}" \
        --build-arg NEXT_PUBLIC_API_URL=https://api-int.rubinobs.com/api \
        --build-arg NEXT_PUBLIC_ASSETS_BASE_URL=https://api-int.rubinobs.com/assets \
        --build-arg NEXT_PUBLIC_ASTRO_API_URL=https://us-central1-rubin-obs.cloudfunctions.net/astro-objects-api \
        --build-arg NEXT_PUBLIC_GOOGLE_APP_ID=688095955960-t0fpaj4ec3gh5vsr9lhg8govapk2oeo9.apps.googleusercontent.com \
        --build-arg NEXT_PUBLIC_PAGEPROOFER_ID=0a40ceaf-340d-5e6a-adc7-898f09823859 \
        --build-arg NEXT_PUBLIC_SHARETHIS_PROPERTY=5f57f7661db73a00129d7d03 \
        --build-arg NEXT_PUBLIC_CONTACT_FORM_POST_URL=something \
        .
    - name: Configure Docker Auth
      run: gcloud --quiet auth configure-docker

    - name: Push Container Image to GCR
      run: docker push gcr.io/${{ secrets.SV_PROJ_NAME }}/rubin-obs-client:${{ github.sha }}

    - name: Format version name
      id: version_name
      run: echo "version_name=$(echo \"${{ github.head_ref }}\" | tr -cd '[:alnum:]' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Deploy branch-tagged version to App Engine
      run: |-
        gcloud app deploy app.yaml \
        --image-url=gcr.io/${{ secrets.SV_PROJ_NAME }}/rubin-obs-client:${{ github.sha }} \
        --version=${{ env.version_name }} \
        --no-promote \
        --project=${{ secrets.SV_PROJ_NAME }}
    
    - name: Get the version URL
      id: get_version
      run: echo "version_url=$(gcloud app versions list --uri --service=default --filter=version.id:${{ env.version_name }})" >> $GITHUB_ENV

    - name: Post the URL to the PR
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          A preview of this PR will be available at ${{ env.version_url }} until the request is closed.
        reactions: '+1'

  cleanup:
    name: 'Cleanup PR Preview'
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'closed'}}

    # Checkout the repository to the GitHub Actions runner
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # gcloud CLI setup
    - name: Login to GCP
      uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.DEV_SA_KEY }}
        project_id: ${{ secrets.SV_PROJ_NAME }}
        export_default_credentials: true        

    - name: Format version name
      id: version_name
      run: echo "version_name=$(echo \"${{ github.head_ref }}\" | tr -cd '[:alnum:]' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      
    # Destruct!
    - name: Destroy version
      run: gcloud app versions delete ${{ env.version_name }} --service=default